import turtle
pen = turtle.Turtle()
turtle.bgcolor("white")
pen.color("red")
pen.pensize(5)
pen.begin_fill()
for _ in range(8):
    pen.forward(80)
    pen.left(45)
pen.end_fill()
pen.penup()
pen.goto(2, 60)
pen.color("white")
turtle.color("white")
turtle.pensize(7)
turtle.penup()
turtle.goto(1,10)
turtle.pendown()
turtle.forward(75)
turtle.left(45)
turtle.forward(70)
turtle.left(45)
turtle.forward(75)
turtle.left(45)
turtle.forward(70)
turtle.left(45)
turtle.forward(70)
turtle.left(45)
turtle.forward(75)
turtle.left(45)
turtle.forward(70)
turtle.left(45)
turtle.forward(70)
pen.goto(40,70)
pen.write("STOP",align="center", font=("Arial", 50, "bold"))
